site_name: Rayd.io
site_url: "https://rayd.io/"
site_author: Simon Schneider <developer@raynigon.de>
site_description: "Rayd.io is a simple web radio client"
copyright: "Rayd.io is licensed under the <a href='https://github.com/raynigon/raydio/blob/master/LICENSE.md'>Apache 2.0 license</a>"

plugins:
  - search
  - markdownextradata
theme:
  name: cinder
  font: false
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'
repo_name: 'GitHub'
repo_url: 'https://github.com/raynigon/raydio'
edit_uri: 'edit/main/docs/'
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      linenums: False
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
nav:
  - Home: index.md
  - Installation:
      - Linux: installation/linux.md
      - Docker: installation/docker.md
      - MacOS: installation/macos.md
      - Windows: installation/windows.md
  - Configuration: config.md
  - Usage:
      - Web App Installation: usage/webapp-installation.md
  - Imprint: http://raynigon.de/impressum.html
extra:
  latest_version: 1.1.0
