#=======================================
# Spring Boot Framework Configuration
#=======================================
spring:
  # This should enable a faster startup,
  # but the first http call will be much slower
  main.lazy-initialization: true
  datasource:
    url: "jdbc:sqlite:development_db.sqlite"
    hikari:
      maximumPoolSize: 1
  jpa:
    database-platform: "org.sqlite.hibernate.dialect.SQLiteDialect"
server.jetty.threads.acceptors: 3
#=======================================
# Raydio Application Configuration
#=======================================
raydio:
  webradio:
    directory:
      url: "https://stations.rayd.io/v1/"