name: CD

on:
  push:
    branches: [ main ]

jobs:
  build_frontend:
    name: "Build Frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Install Packages
        run: npm i
        working-directory: frontend
      - name: Build Production Frontend
        run: npm run build
        working-directory: frontend
      - name: Upload Frontend
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Frontend"
          path: "frontend/dist/raydio/"
  build_jar:
    name: "Build Jar Archive"
    runs-on: ubuntu-latest
    needs: [ build_frontend ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - uses: actions/download-artifact@v2
        with:
          name: "Frontend"
          path: src/main/resources/static/
      - name: Build Jar Archive
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "build -x test"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - name: Jar Archive
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Jar Archive"
          path: "build/libs/"
  build_docker:
    name: "Build Docker Container"
    runs-on: ubuntu-latest
    needs: [ build_frontend ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - uses: actions/download-artifact@v2
        with:
          name: "Frontend"
          path: src/main/resources/static/
      - name: Build Docker Container
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "jibDockerBuild -x test"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
  build_packages:
    name: "Build Linux Packages"
    runs-on: ubuntu-latest
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - uses: actions/download-artifact@v2
        with:
          name: "Frontend"
          path: src/main/resources/static/
      - name: "Build Packages (.deb, .rpm)"
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "buildDeb buildRpm -x test"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - name: Upload Packages
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Linux Packages"
          path: "build/distributions/"
