name: CD

on:
  push:
    branches: [ main ]

jobs:
  build_docker:
    name: "Build Docker Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Build Docker Container
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "jibDockerBuild"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - name: Test Docker Container
        run: |
          docker run --rm -d -p 8080:8080 raydio
          counter=10
          while [ $counter -ge 0 ]
          do
            curl http://localhost:8080/api/v1/webradio/
            if ($? == 0)
            then
            	exit 0
            fi
            sleep 1
            counter=$(( $counter - 1 ))
          done
          exit 1
  build_packages:
    name: "Build Linux Packages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: "Build .deb, .rpm Packages"
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "buildDeb buildRpm"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - name: Upload Packages
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Linux Packages"
          path: "build/distributions/"
