name: CI-PR

on:
  push:
    branches: [ ]

jobs:
  backend_lint:
    name: "Backend Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Run Gradle Tests
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "ktlintCheck"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
  backend_test:
    name: "Backend Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Run Gradle Tests
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "clean test"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
      - name: Codacy Publish
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
  frontend_lint:
    name: "Frontend Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Install Packages
        run: npm i
        working-directory: frontend
      - name: Build Production
        run: npx ng lint
        working-directory: frontend
  frontend_test:
    name: "Frontend Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Install Packages
        run: npm i
        working-directory: frontend
      - name: Build Production
        run: npm run build
        working-directory: frontend
