name: CI-PR

on:
  push:
    branches: [ ]

jobs:
  backend_test:
    name: "Backend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Run Gradle Tests
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: "clean test"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
  frontend_test:
    name: "Frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Install Packages
        run: npm i
      - name: Build Production
        run: npm run build:prod