name: CI-PR

on:
  push:
    branches: [ ]

jobs:
  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
      - name: Run Gradle Tests
        run: ./gradlew test